# Generated by Django 6.0.2 on 2026-03-15 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاريخ الموعد')),
                ('time', models.CharField(max_length=10, verbose_name='وقت الموعد (HH:MM)')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة — في انتظار تأكيد الدفع'), ('Confirmed', 'مؤكد'), ('Attended', 'حضر وانتهى الكشف'), ('No-Show', 'لم يحضر المريض'), ('Cancelled', 'ملغي')], db_index=True, default='Pending', max_length=20, verbose_name='الحالة')),
                ('payment_type', models.CharField(choices=[('Full', 'دفع كامل'), ('Deposit', 'دفع عربون'), ('PayAtClinic', 'دفع في العيادة')], default='Full', max_length=20, verbose_name='نوع الدفع')),
                ('booking_code', models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='كود الحجز')),
                ('complaint', models.TextField(blank=True, verbose_name='الشكوى / سبب الزيارة')),
                ('is_manual', models.BooleanField(default=False, verbose_name='حجز يدوي؟')),
                ('patient_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المريض (يدوي)')),
                ('patient_phone', models.CharField(blank=True, max_length=15, verbose_name='رقم المريض (يدوي)')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تمت التسوية؟')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Vodafone', 'فودافون كاش'), ('Instapay', 'إنستا باي'), ('Cash', 'دفع في العيادة'), ('Fawry', 'فوري')], default='Cash', max_length=20, verbose_name='طريقة الدفع')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق؟')),
                ('paymob_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_cents', models.IntegerField(default=0, verbose_name='المبلغ بالقروش')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='bookings.appointment', verbose_name='الموعد')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'المدفوعات',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العيادة / المجمع الطبي')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن العيادة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinic_images/', verbose_name='صورة العيادة')),
                ('is_multi_specialty', models.BooleanField(default=False, help_text='لو True → المريض يختار التخصص أولاً ثم الدكتور', verbose_name='مجمع طبي متعدد التخصصات؟')),
                ('location', models.CharField(choices=[('Abbaseya', 'العباسية'), ('Nasr City', 'مدينة نصر'), ('New Cairo', 'التجمع الخامس'), ('Maadi', 'المعادي'), ('Shoubra', 'شبرا'), ('Dokki', 'الدقي'), ('Giza', 'الجيزة'), ('Zamalek', 'الزمالك'), ('Haram', 'الهرم'), ('Faisal', 'فيصل'), ('Obour', 'العبور'), ('Shorouk', 'الشروق'), ('October', '6 أكتوبر'), ('Sheikh Zayed', 'الشيخ زايد'), ('Helwan', 'حلوان'), ('Mokattam', 'المقطم'), ('Alexandria', 'الإسكندرية')], default='Nasr City', max_length=50, verbose_name='المنطقة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان بالتفصيل')),
                ('google_map_link', models.URLField(blank=True, null=True, verbose_name='رابط جوجل ماب')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='رقم العيادة')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, verbose_name='واتساب')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة عمولة الموقع (%)')),
                ('is_available', models.BooleanField(default=True, verbose_name='تقبل حجوزات جديدة؟')),
                ('is_new', models.BooleanField(default=True, verbose_name='عيادة جديدة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='مالك العيادة')),
            ],
            options={
                'verbose_name': 'عيادة',
                'verbose_name_plural': 'العيادات',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدكتور')),
                ('title', models.CharField(choices=[('dr', 'د.'), ('prof', 'أ.د.'), ('consultant', 'استشاري')], default='dr', max_length=20, verbose_name='اللقب')),
                ('specialty', models.CharField(choices=[('general', 'طب عام'), ('internal', 'باطنة'), ('cardiology', 'قلب وأوعية دموية'), ('orthopedics', 'عظام'), ('pediatrics', 'أطفال'), ('dermatology', 'جلدية وتجميل'), ('gynecology', 'نساء وتوليد'), ('ophthalmology', 'عيون'), ('ent', 'أنف وأذن وحنجرة'), ('neurology', 'مخ وأعصاب'), ('psychiatry', 'نفسية'), ('dentistry', 'أسنان'), ('urology', 'مسالك بولية'), ('oncology', 'أورام'), ('endocrinology', 'غدد صماء وسكر'), ('other', 'أخرى')], default='general', max_length=30, verbose_name='التخصص')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة عن الدكتور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='صورة الدكتور')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الكشف (ج.م)')),
                ('slot_duration', models.IntegerField(default=30, verbose_name='مدة الكشف (بالدقائق)')),
                ('opening_hour', models.IntegerField(default=9, verbose_name='بداية الدوام (ساعة)')),
                ('closing_hour', models.IntegerField(default=17, verbose_name='نهاية الدوام (ساعة)')),
                ('works_sat', models.BooleanField(default=True, verbose_name='السبت')),
                ('works_sun', models.BooleanField(default=True, verbose_name='الأحد')),
                ('works_mon', models.BooleanField(default=True, verbose_name='الاثنين')),
                ('works_tue', models.BooleanField(default=True, verbose_name='الثلاثاء')),
                ('works_wed', models.BooleanField(default=True, verbose_name='الأربعاء')),
                ('works_thu', models.BooleanField(default=True, verbose_name='الخميس')),
                ('works_fri', models.BooleanField(default=False, verbose_name='الجمعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للحجز؟')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='bookings.clinic', verbose_name='العيادة')),
            ],
            options={
                'verbose_name': 'دكتور',
                'verbose_name_plural': 'الدكاترة',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bookings.doctor', verbose_name='الدكتور'),
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.doctor', verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الموبايل')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Cancelled', 'No-Show']), _negated=True), fields=('doctor', 'date', 'time'), name='unique_active_appointment'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorreview',
            unique_together={('doctor', 'patient')},
        ),
    ]
