# Generated by Django 6.0.2 on 2026-02-14 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الملعب')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الساعة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pitch_images/', verbose_name='صورة الملعب')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='العنوان نصياً')),
                ('google_map_link', models.URLField(blank=True, null=True, verbose_name='رابط جوجل ماب')),
                ('description', models.TextField(blank=True, verbose_name='وصف ومميزات الملعب')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='رقم هاتف الحجز/الاستفسار')),
                ('size', models.CharField(choices=[('5x5', 'خماسي (5 ضد 5)'), ('7x7', 'سباعي (7 ضد 7)'), ('11x11', 'قانوني (11 ضد 11)')], default='5x5', max_length=10, verbose_name='حجم الملعب')),
                ('floor_type', models.CharField(choices=[('Artificial', 'نجيل صناعي'), ('Natural', 'نجيل طبيعي'), ('Tartan', 'ترتان / مطاط')], default='Artificial', max_length=20, verbose_name='نوع الأرضية')),
                ('has_showers', models.BooleanField(default=False, verbose_name='يوجد حمامات/دش')),
                ('has_parking', models.BooleanField(default=False, verbose_name='يوجد جراج')),
                ('has_ball', models.BooleanField(default=True, verbose_name='توفر كرة')),
                ('has_bibs', models.BooleanField(default=False, verbose_name='توفر ماركرات (صديري)')),
            ],
            options={
                'verbose_name': 'ملعب',
                'verbose_name_plural': 'الملاعب',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الحجز')),
                ('time', models.CharField(max_length=10, verbose_name='وقت الحجز')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار (مطلوب)'), ('Confirmed', 'تم التأكيد'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت إنشاء الطلب')),
                ('booking_code', models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='كود الحجز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.pitch', verbose_name='الملعب')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية / التحويل')),
                ('payment_method', models.CharField(choices=[('Vodafone', 'فودافون كاش'), ('Instapay', 'إنستا باي'), ('Cash', 'دفع في الملعب')], default='Cash', max_length=20, verbose_name='طريقة الدفع')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الدفع؟')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدفع')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='bookings.booking', verbose_name='الحجز المرتبط')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'المدفوعات',
            },
        ),
    ]
