# Generated by Django 6.0.2 on 2026-02-14 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم صاحب الملعب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Vodafone', 'فودافون كاش'), ('Instapay', 'إنستا باي'), ('Cash', 'دفع في الملعب'), ('Fawry', 'فوري')], default='Cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الملعب'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='التقييم (من 5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.pitch', verbose_name='الملعب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
