# Generated by Django 6.0.2 on 2026-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح الآن؟'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='ملعب جديد؟'),
        ),
    ]
