# Generated by Django 6.0.2 on 2026-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_pitch_owner_name_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول (Longitude)'),
        ),
    ]
