# Generated by Django 6.0.2 on 2026-02-13 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booking_date_booking_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'حجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'عملية دفع', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name': 'ملعب', 'verbose_name_plural': 'الملاعب'},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='كود الحجز'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='وقت إنشاء الطلب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Vodafone', 'فودافون كاش'), ('Instapay', 'إنستا باي'), ('Cash', 'دفع في الملعب')], default='Cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='وقت الدفع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.pitch', verbose_name='الملعب'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار (مطلوب)'), ('Confirmed', 'تم التأكيد'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=10, verbose_name='وقت الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='bookings.booking', verbose_name='الحجز المرتبط'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الدفع؟'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية / التحويل'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الملعب'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الساعة'),
        ),
    ]
