# Generated by Django 6.0.2 on 2026-02-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_pitch_is_available_pitch_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='closing_hour',
            field=models.IntegerField(default=24, verbose_name='ساعة الغلق (مثال: 24 يعني 12 بالليل)'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='opening_hour',
            field=models.IntegerField(default=8, verbose_name='ساعة الفتح (مثال: 8 يعني 8 صباحاً)'),
        ),
    ]
