# Generated by Django 6.0.2 on 2026-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف ومميزات الملعب'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='floor_type',
            field=models.CharField(choices=[('Artificial', 'نجيل صناعي'), ('Natural', 'نجيل طبيعي'), ('Tartan', 'ترتان / مطاط')], default='Artificial', max_length=20, verbose_name='نوع الأرضية'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='google_map_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط جوجل ماب'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_ball',
            field=models.BooleanField(default=True, verbose_name='توفر كرة'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_bibs',
            field=models.BooleanField(default=False, verbose_name='توفر ماركرات (صديري)'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='يوجد جراج'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_showers',
            field=models.BooleanField(default=False, verbose_name='يوجد حمامات/دش'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_images/', verbose_name='صورة الملعب'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان نصياً'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم هاتف الحجز/الاستفسار'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='size',
            field=models.CharField(choices=[('5x5', 'خماسي (5 ضد 5)'), ('7x7', 'سباعي (7 ضد 7)'), ('11x11', 'قانوني (11 ضد 11)')], default='5x5', max_length=10, verbose_name='حجم الملعب'),
        ),
    ]
