# Generated by Django 6.0.2 on 2026-02-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_pitch_latitude_pitch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('Full', 'دفع كامل'), ('Deposit', 'دفع عربون (50 ج.م)'), ('PayAtPitch', 'دفع في الملعب (للمميزين فقط)')], default='Full', max_length=20, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة (انتظار التأكيد)'), ('Confirmed', 'تم التأكيد'), ('Cancelled', 'ملغي / مرفوض')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الساعة الأساسي'),
        ),
        migrations.CreateModel(
            name='PitchPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='تاريخ معين (اختياري)')),
                ('start_hour', models.IntegerField(default=0, verbose_name='من الساعة (مثلاً 5 فجراً)')),
                ('end_hour', models.IntegerField(default=24, verbose_name='إلى الساعة (مثلاً 16 عصراً)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الخاص في هذا الوقت')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.pitch', verbose_name='الملعب')),
            ],
            options={
                'verbose_name': 'سعر خاص / خصم',
                'verbose_name_plural': 'قائمة الأسعار الخاصة',
            },
        ),
    ]
