# Generated by Django 6.0.2 on 2026-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_pitch_closing_hour_pitch_opening_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_cents',
            field=models.IntegerField(default=0, verbose_name='المبلغ بالقروش'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paymob Order ID'),
        ),
    ]
