# Generated by Django 6.0.2 on 2026-02-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_type_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='location',
            field=models.CharField(choices=[('Abbaseya', 'العباسية'), ('Nasr City', 'مدينة نصر'), ('New Cairo', 'مصر الجديدة'), ('Maadi', 'المعادي'), ('Shoubra', 'شبرا'), ('Dokki', 'الدقي'), ('Giza', 'الجيزة'), ('Zamalek', 'الزمالك'), ('Haram', 'الهرم'), ('Faisal', 'فيصل'), ('Obour', 'العبور'), ('Shorouk', 'الشروق'), ('October', '6 أكتوبر'), ('Sheikh Zayed', 'الشيخ زايد'), ('Helwan', 'حلوان'), ('Mokattam', 'المقطم')], default='Nasr City', max_length=50, verbose_name='المنطقة'),
        ),
    ]
