# Generated by Django 6.0.2 on 2026-03-05 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_payment_amount_cents_payment_paymob_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('pitch', 'date', 'time'), name='unique_active_booking'),
        ),
    ]
