# Generated by Django 6.0.2 on 2026-03-05 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_unique_active_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم العميل (للحجز اليدوي)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم العميل (للحجز اليدوي)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='حجز يدوي؟'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pitches', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الملعب (حساب المستخدم)'),
        ),
    ]
