# Generated by Django 6.0.2 on 2026-03-07 18:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_userprofile_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking',
        ),
        migrations.AddField(
            model_name='pitch',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='مثال: 5.00 يعني 5%', max_digits=5, verbose_name='نسبة عمولة الموقع (%)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة (انتظار التأكيد)'), ('Confirmed', 'تم التأكيد'), ('Played', 'اكتمل (تم اللعب والدفع)'), ('No-Show', 'لم يحضر العميل (إلغاء)'), ('Cancelled', 'ملغي / مرفوض')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم (من 5)'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Cancelled', 'No-Show']), _negated=True), fields=('pitch', 'date', 'time'), name='unique_active_booking'),
        ),
    ]
