# Generated by Django 6.0.2 on 2026-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_booking_unique_active_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='يُحدَّث تلقائياً عند تسوية الحساب مع صاحب الملعب', verbose_name='تمت التسوية؟'),
        ),
    ]
