# Generated by Django 6.0.2 on 2026-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة (انتظار التأكيد)'), ('Confirmed', 'تم التأكيد'), ('Played', 'اكتمل (تم اللعب والدفع)'), ('No-Show', 'لم يحضر العميل (إلغاء)'), ('Cancelled', 'ملغي / مرفوض')], db_index=True, default='Pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
